stages:
  - prepare
  - check
  - publish
  - notify

prepare:
  stage: prepare
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - npm ci
    - tar -czf "node_modules.tar.gz" ./node_modules
  artifacts:
    paths:
      - node_modules.tar.gz
    expire_in: 1 day

checks:
  stage: check
  tags:
    - matt.sebbo.net
    - ssh
  except:
    - tags
  script:
    - tar -xzf "node_modules.tar.gz" -C .
    - rm -f ./node_modules.tar.gz
    - npm run check

publish_github:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  retry: 2
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - git pull
    - git push "https://${GITHUB_AUTH}@github.com/ubud-app/client.git" --all
    - git push "https://${GITHUB_AUTH}@github.com/ubud-app/client.git" --tags
  only:
    - tags
    - master
    - develop

publish_npm_next:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - tar -xzf "node_modules.tar.gz" -C .
    - rm -f ./node_modules.tar.gz
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - export OLDVERSION=$(npm view @ubud-app/client@next version)
    - jq -M ".version=\"$OLDVERSION\"" package.json|sponge package.json
    - npm --no-git-tag-version version prerelease
    - export NEWVERSION=$(cat ./package.json| jq -rM '.version')
    - npx sentry-cli releases new "$NEWVERSION"
    - npx sentry-cli releases set-commits --auto $NEWVERSION
    - npm run build
    - npm publish --tag "next"
    - npx sentry-cli releases finalize "$NEWVERSION"
  only:
    - develop

publish_npm:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - tar -xzf "node_modules.tar.gz" -C .
    - rm -f ./node_modules.tar.gz
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - jq -M ".version=\"$CI_COMMIT_TAG\"" package.json|sponge package.json
    - npx sentry-cli releases new "$CI_COMMIT_TAG"
    - npx sentry-cli releases set-commits --auto $CI_COMMIT_TAG
    - npm run build
    - npm publish
    - npx sentry-cli releases finalize "$CI_COMMIT_TAG"
  only:
    - tags

notify:
  stage: notify
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - curl -X "POST" "https://beacon.ubud.club/webhooks/update-components/${NOTIFY_WEBHOOK_SECRET}"
  only:
    - develop
    - tags
