stages:
  - build
  - check
  - publish
  - done

publish_github:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - git push "https://${GITHUB_AUTH}@github.com/sebbo2002/dwimm-client.git" --all
    - git push "https://${GITHUB_AUTH}@github.com/sebbo2002/dwimm-client.git" --tags

check_lint:
  stage: check
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - yarn install
    - yarn run check


visualize:
  stage: check
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - yarn install
    - npm run visualize
    - rm -rf /var/docker/static/dwimm/client-web/plato/*
    - mv ./code-visualization/* /var/docker/static/dwimm/client-web/plato/


publish_npm_next:
  stage: publish
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - node -v
    - yarn -v
    - yarn install
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - npm run bump:develop
    - npm run build
    - echo $(cat ./package.json | jq '.version' -rce)
    - npm publish --tag "next"
  only:
    - develop


build_server:
  stage: done
  tags:
      - matt.sebbo.net
      - ssh
  script:
      - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://git.sebbo.net/api/v4/projects/67/trigger/pipeline
