name: Test
on:
  push:
    branches:
      - feature/**
      - hotfix/**
      - depfu/**

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [8, 10, 12, 13, 14]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: modules-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v2
        id: module-cache
        with:
          path: ~/.npm
          key: npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        if: steps.module-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: test
        run: npm run test
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        id: module-cache
        with:
          path: node_modules
          key: modules-12-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: npm-12-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci
        if: steps.module-cache.outputs.cache-hit != 'true' || steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run check
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v2
        id: module-cache
        with:
          path: node_modules
          key: modules-12-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        if: steps.module-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: install zopfli
        run: |
          npm i -g grunt-cli
          git clone https://github.com/google/zopfli.git ./.devcache/zopfli
          cd ./.devcache/zopfli
          make
          cd ../../
      - name: build
        run: PATH="$(pwd)/.devcache/zopfli:$PATH" npm run build
